import { Metadata } from "next";
import Navigation from "../components/navigation";

//default 가 %s에 들어감
export const metadata: Metadata = {
  title: { template: "%s | Next Movies", default: "Loading..." },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
